version: "3.1"
services:
  gateway:
    image: traefik:2.2
    command: --api.insecure --providers.docker --entrypoints.web.address=:80
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  api:
    # image: ee-api
    image: node:16-alpine
    command: yarn --cwd /app/services/api start:dev
    user: "${UID_GID}"
    volumes:
      - "./services/api:/app/services/api"
    environment:
      - "PORT=3000"
    labels:
      - "traefik.http.routers.api.rule=HostRegexp(`myapp.127-0-0-1.nip.io`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  frontend:
    # image: ee-frontend
    image: node:16-alpine
    command: yarn --cwd /app/services/frontend start:dev --host
    user: "${UID_GID}"
    volumes:
      - "./services/frontend:/app/services/frontend"
    environment:
      - "PROXIED_PORT=80"
    labels:
      - "traefik.http.routers.frontend.rule=HostRegexp(`myapp.127-0-0-1.nip.io`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
